---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: run-keeping-up-with-upstream-
spec:
  pipelineRef:
    name: keeping-up-with-upstream
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi